/* tslint:disable */
/* eslint-disable */
/**
 * AI Proxy API
 * OpenAI-compatible proxy for llama.cpp with context compression, retry, and tool-call buffering
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ToolCallDto } from './ToolCallDto';
import {
    ToolCallDtoFromJSON,
    ToolCallDtoFromJSONTyped,
    ToolCallDtoToJSON,
    ToolCallDtoToJSONTyped,
} from './ToolCallDto';

/**
 * 
 * @export
 * @interface ChatMessageDto
 */
export interface ChatMessageDto {
    /**
     * Role of the message sender: system, user, assistant, or tool
     * @type {string}
     * @memberof ChatMessageDto
     */
    role: string;
    /**
     * Message content (string for text, array for multimodal/vision)
     * @type {string}
     * @memberof ChatMessageDto
     */
    content?: string;
    /**
     * 
     * @type {Array<ToolCallDto>}
     * @memberof ChatMessageDto
     */
    toolCalls?: Array<ToolCallDto>;
    /**
     * 
     * @type {string}
     * @memberof ChatMessageDto
     */
    toolCallId?: string;
    /**
     * Reasoning content from llama.cpp thinking models (non-standard OpenAI field)
     * @type {string}
     * @memberof ChatMessageDto
     */
    reasoningContent?: string;
}

/**
 * Check if a given object implements the ChatMessageDto interface.
 */
export function instanceOfChatMessageDto(value: object): value is ChatMessageDto {
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function ChatMessageDtoFromJSON(json: any): ChatMessageDto {
    return ChatMessageDtoFromJSONTyped(json, false);
}

export function ChatMessageDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatMessageDto {
    if (json == null) {
        return json;
    }
    return {
        
        'role': json['role'],
        'content': json['content'] == null ? undefined : json['content'],
        'toolCalls': json['tool_calls'] == null ? undefined : ((json['tool_calls'] as Array<any>).map(ToolCallDtoFromJSON)),
        'toolCallId': json['tool_call_id'] == null ? undefined : json['tool_call_id'],
        'reasoningContent': json['reasoning_content'] == null ? undefined : json['reasoning_content'],
    };
}

export function ChatMessageDtoToJSON(json: any): ChatMessageDto {
    return ChatMessageDtoToJSONTyped(json, false);
}

export function ChatMessageDtoToJSONTyped(value?: ChatMessageDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role': value['role'],
        'content': value['content'],
        'tool_calls': value['toolCalls'] == null ? undefined : ((value['toolCalls'] as Array<any>).map(ToolCallDtoToJSON)),
        'tool_call_id': value['toolCallId'],
        'reasoning_content': value['reasoningContent'],
    };
}

