/* tslint:disable */
/* eslint-disable */
/**
 * AI Proxy API
 * OpenAI-compatible proxy for llama.cpp with context compression, retry, and tool-call buffering
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatChoiceDto } from './ChatChoiceDto';
import {
    ChatChoiceDtoFromJSON,
    ChatChoiceDtoFromJSONTyped,
    ChatChoiceDtoToJSON,
    ChatChoiceDtoToJSONTyped,
} from './ChatChoiceDto';
import type { UsageDto } from './UsageDto';
import {
    UsageDtoFromJSON,
    UsageDtoFromJSONTyped,
    UsageDtoToJSON,
    UsageDtoToJSONTyped,
} from './UsageDto';

/**
 * 
 * @export
 * @interface ChatCompletionResponseDto
 */
export interface ChatCompletionResponseDto {
    /**
     * 
     * @type {string}
     * @memberof ChatCompletionResponseDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ChatCompletionResponseDto
     */
    object: string;
    /**
     * 
     * @type {number}
     * @memberof ChatCompletionResponseDto
     */
    created: number;
    /**
     * 
     * @type {string}
     * @memberof ChatCompletionResponseDto
     */
    model: string;
    /**
     * 
     * @type {Array<ChatChoiceDto>}
     * @memberof ChatCompletionResponseDto
     */
    choices: Array<ChatChoiceDto>;
    /**
     * 
     * @type {UsageDto}
     * @memberof ChatCompletionResponseDto
     */
    usage?: UsageDto;
}

/**
 * Check if a given object implements the ChatCompletionResponseDto interface.
 */
export function instanceOfChatCompletionResponseDto(value: object): value is ChatCompletionResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('choices' in value) || value['choices'] === undefined) return false;
    return true;
}

export function ChatCompletionResponseDtoFromJSON(json: any): ChatCompletionResponseDto {
    return ChatCompletionResponseDtoFromJSONTyped(json, false);
}

export function ChatCompletionResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'object': json['object'],
        'created': json['created'],
        'model': json['model'],
        'choices': ((json['choices'] as Array<any>).map(ChatChoiceDtoFromJSON)),
        'usage': json['usage'] == null ? undefined : UsageDtoFromJSON(json['usage']),
    };
}

export function ChatCompletionResponseDtoToJSON(json: any): ChatCompletionResponseDto {
    return ChatCompletionResponseDtoToJSONTyped(json, false);
}

export function ChatCompletionResponseDtoToJSONTyped(value?: ChatCompletionResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'object': value['object'],
        'created': value['created'],
        'model': value['model'],
        'choices': ((value['choices'] as Array<any>).map(ChatChoiceDtoToJSON)),
        'usage': UsageDtoToJSON(value['usage']),
    };
}

