/* tslint:disable */
/* eslint-disable */
/**
 * AI Proxy API
 * OpenAI-compatible proxy for llama.cpp with context compression, retry, and tool-call buffering
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ToolDefinitionDto } from './ToolDefinitionDto';
import {
    ToolDefinitionDtoFromJSON,
    ToolDefinitionDtoFromJSONTyped,
    ToolDefinitionDtoToJSON,
    ToolDefinitionDtoToJSONTyped,
} from './ToolDefinitionDto';
import type { ChatMessageDto } from './ChatMessageDto';
import {
    ChatMessageDtoFromJSON,
    ChatMessageDtoFromJSONTyped,
    ChatMessageDtoToJSON,
    ChatMessageDtoToJSONTyped,
} from './ChatMessageDto';
import type { CompressionOptionsDto } from './CompressionOptionsDto';
import {
    CompressionOptionsDtoFromJSON,
    CompressionOptionsDtoFromJSONTyped,
    CompressionOptionsDtoToJSON,
    CompressionOptionsDtoToJSONTyped,
} from './CompressionOptionsDto';

/**
 * 
 * @export
 * @interface ChatCompletionRequestDto
 */
export interface ChatCompletionRequestDto {
    /**
     * 
     * @type {Array<ChatMessageDto>}
     * @memberof ChatCompletionRequestDto
     */
    messages: Array<ChatMessageDto>;
    /**
     * 
     * @type {string}
     * @memberof ChatCompletionRequestDto
     */
    model?: string;
    /**
     * 
     * @type {number}
     * @memberof ChatCompletionRequestDto
     */
    temperature?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ChatCompletionRequestDto
     */
    stream?: boolean;
    /**
     * 
     * @type {Array<ToolDefinitionDto>}
     * @memberof ChatCompletionRequestDto
     */
    tools?: Array<ToolDefinitionDto>;
    /**
     * 
     * @type {object}
     * @memberof ChatCompletionRequestDto
     */
    toolChoice?: object;
    /**
     * 
     * @type {number}
     * @memberof ChatCompletionRequestDto
     */
    maxTokens?: number;
    /**
     * Proxy extension: context compression options
     * @type {CompressionOptionsDto}
     * @memberof ChatCompletionRequestDto
     */
    compressionOptions?: CompressionOptionsDto;
    /**
     * Proxy extension: buffer all tool-call deltas before sending to client (only meaningful when stream=true)
     * @type {boolean}
     * @memberof ChatCompletionRequestDto
     */
    awaitToolCallCompletion?: boolean;
    /**
     * Proxy extension: disable thinking/reasoning for llama.cpp models that support it (defaults to false)
     * @type {boolean}
     * @memberof ChatCompletionRequestDto
     */
    disableThinking?: boolean;
}

/**
 * Check if a given object implements the ChatCompletionRequestDto interface.
 */
export function instanceOfChatCompletionRequestDto(value: object): value is ChatCompletionRequestDto {
    if (!('messages' in value) || value['messages'] === undefined) return false;
    return true;
}

export function ChatCompletionRequestDtoFromJSON(json: any): ChatCompletionRequestDto {
    return ChatCompletionRequestDtoFromJSONTyped(json, false);
}

export function ChatCompletionRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'messages': ((json['messages'] as Array<any>).map(ChatMessageDtoFromJSON)),
        'model': json['model'] == null ? undefined : json['model'],
        'temperature': json['temperature'] == null ? undefined : json['temperature'],
        'stream': json['stream'] == null ? undefined : json['stream'],
        'tools': json['tools'] == null ? undefined : ((json['tools'] as Array<any>).map(ToolDefinitionDtoFromJSON)),
        'toolChoice': json['tool_choice'] == null ? undefined : json['tool_choice'],
        'maxTokens': json['max_tokens'] == null ? undefined : json['max_tokens'],
        'compressionOptions': json['compressionOptions'] == null ? undefined : CompressionOptionsDtoFromJSON(json['compressionOptions']),
        'awaitToolCallCompletion': json['awaitToolCallCompletion'] == null ? undefined : json['awaitToolCallCompletion'],
        'disableThinking': json['disableThinking'] == null ? undefined : json['disableThinking'],
    };
}

export function ChatCompletionRequestDtoToJSON(json: any): ChatCompletionRequestDto {
    return ChatCompletionRequestDtoToJSONTyped(json, false);
}

export function ChatCompletionRequestDtoToJSONTyped(value?: ChatCompletionRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'messages': ((value['messages'] as Array<any>).map(ChatMessageDtoToJSON)),
        'model': value['model'],
        'temperature': value['temperature'],
        'stream': value['stream'],
        'tools': value['tools'] == null ? undefined : ((value['tools'] as Array<any>).map(ToolDefinitionDtoToJSON)),
        'tool_choice': value['toolChoice'],
        'max_tokens': value['maxTokens'],
        'compressionOptions': CompressionOptionsDtoToJSON(value['compressionOptions']),
        'awaitToolCallCompletion': value['awaitToolCallCompletion'],
        'disableThinking': value['disableThinking'],
    };
}

