/* tslint:disable */
/* eslint-disable */
/**
 * AI Proxy API
 * OpenAI-compatible proxy for llama.cpp with context compression, retry, and tool-call buffering
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatMessageDto } from './ChatMessageDto';
import {
    ChatMessageDtoFromJSON,
    ChatMessageDtoFromJSONTyped,
    ChatMessageDtoToJSON,
    ChatMessageDtoToJSONTyped,
} from './ChatMessageDto';

/**
 * 
 * @export
 * @interface ChatChoiceDto
 */
export interface ChatChoiceDto {
    /**
     * 
     * @type {number}
     * @memberof ChatChoiceDto
     */
    index: number;
    /**
     * 
     * @type {ChatMessageDto}
     * @memberof ChatChoiceDto
     */
    message: ChatMessageDto;
    /**
     * 
     * @type {string}
     * @memberof ChatChoiceDto
     */
    finishReason?: string;
}

/**
 * Check if a given object implements the ChatChoiceDto interface.
 */
export function instanceOfChatChoiceDto(value: object): value is ChatChoiceDto {
    if (!('index' in value) || value['index'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ChatChoiceDtoFromJSON(json: any): ChatChoiceDto {
    return ChatChoiceDtoFromJSONTyped(json, false);
}

export function ChatChoiceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatChoiceDto {
    if (json == null) {
        return json;
    }
    return {
        
        'index': json['index'],
        'message': ChatMessageDtoFromJSON(json['message']),
        'finishReason': json['finish_reason'] == null ? undefined : json['finish_reason'],
    };
}

export function ChatChoiceDtoToJSON(json: any): ChatChoiceDto {
    return ChatChoiceDtoToJSONTyped(json, false);
}

export function ChatChoiceDtoToJSONTyped(value?: ChatChoiceDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'index': value['index'],
        'message': ChatMessageDtoToJSON(value['message']),
        'finish_reason': value['finishReason'],
    };
}

