/* tslint:disable */
/* eslint-disable */
/**
 * AI Proxy API
 * OpenAI-compatible proxy for llama.cpp with context compression, retry, and tool-call buffering
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompressionOptionsDto
 */
export interface CompressionOptionsDto {
    /**
     * Enable context compression before forwarding to llama.cpp
     * @type {boolean}
     * @memberof CompressionOptionsDto
     */
    enabled?: boolean;
    /**
     * Maximum context size in tokens. Older messages are evicted when exceeded.
     * @type {number}
     * @memberof CompressionOptionsDto
     */
    maxContextSize?: number;
}

/**
 * Check if a given object implements the CompressionOptionsDto interface.
 */
export function instanceOfCompressionOptionsDto(value: object): value is CompressionOptionsDto {
    return true;
}

export function CompressionOptionsDtoFromJSON(json: any): CompressionOptionsDto {
    return CompressionOptionsDtoFromJSONTyped(json, false);
}

export function CompressionOptionsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompressionOptionsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'maxContextSize': json['maxContextSize'] == null ? undefined : json['maxContextSize'],
    };
}

export function CompressionOptionsDtoToJSON(json: any): CompressionOptionsDto {
    return CompressionOptionsDtoToJSONTyped(json, false);
}

export function CompressionOptionsDtoToJSONTyped(value?: CompressionOptionsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': value['enabled'],
        'maxContextSize': value['maxContextSize'],
    };
}

