/* tslint:disable */
/* eslint-disable */
/**
 * AI Proxy API
 * OpenAI-compatible proxy for llama.cpp with context compression, retry, and tool-call buffering
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FunctionCallDto
 */
export interface FunctionCallDto {
    /**
     * 
     * @type {string}
     * @memberof FunctionCallDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof FunctionCallDto
     */
    arguments?: string;
}

/**
 * Check if a given object implements the FunctionCallDto interface.
 */
export function instanceOfFunctionCallDto(value: object): value is FunctionCallDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function FunctionCallDtoFromJSON(json: any): FunctionCallDto {
    return FunctionCallDtoFromJSONTyped(json, false);
}

export function FunctionCallDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FunctionCallDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'arguments': json['arguments'] == null ? undefined : json['arguments'],
    };
}

export function FunctionCallDtoToJSON(json: any): FunctionCallDto {
    return FunctionCallDtoToJSONTyped(json, false);
}

export function FunctionCallDtoToJSONTyped(value?: FunctionCallDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'arguments': value['arguments'],
    };
}

