/* tslint:disable */
/* eslint-disable */
/**
 * AI Proxy API
 * OpenAI-compatible proxy for llama.cpp with context compression, retry, and tool-call buffering
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelObjectDto } from './ModelObjectDto';
import {
    ModelObjectDtoFromJSON,
    ModelObjectDtoFromJSONTyped,
    ModelObjectDtoToJSON,
    ModelObjectDtoToJSONTyped,
} from './ModelObjectDto';

/**
 * 
 * @export
 * @interface ModelsListResponseDto
 */
export interface ModelsListResponseDto {
    /**
     * 
     * @type {string}
     * @memberof ModelsListResponseDto
     */
    object: string;
    /**
     * 
     * @type {Array<ModelObjectDto>}
     * @memberof ModelsListResponseDto
     */
    data: Array<ModelObjectDto>;
}

/**
 * Check if a given object implements the ModelsListResponseDto interface.
 */
export function instanceOfModelsListResponseDto(value: object): value is ModelsListResponseDto {
    if (!('object' in value) || value['object'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ModelsListResponseDtoFromJSON(json: any): ModelsListResponseDto {
    return ModelsListResponseDtoFromJSONTyped(json, false);
}

export function ModelsListResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsListResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'object': json['object'],
        'data': ((json['data'] as Array<any>).map(ModelObjectDtoFromJSON)),
    };
}

export function ModelsListResponseDtoToJSON(json: any): ModelsListResponseDto {
    return ModelsListResponseDtoToJSONTyped(json, false);
}

export function ModelsListResponseDtoToJSONTyped(value?: ModelsListResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'object': value['object'],
        'data': ((value['data'] as Array<any>).map(ModelObjectDtoToJSON)),
    };
}

