/* tslint:disable */
/* eslint-disable */
/**
 * AI Proxy API
 * OpenAI-compatible proxy for llama.cpp with context compression, retry, and tool-call buffering
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelObjectDto
 */
export interface ModelObjectDto {
    /**
     * 
     * @type {string}
     * @memberof ModelObjectDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ModelObjectDto
     */
    object: string;
    /**
     * 
     * @type {number}
     * @memberof ModelObjectDto
     */
    created: number;
    /**
     * 
     * @type {string}
     * @memberof ModelObjectDto
     */
    ownedBy: string;
}

/**
 * Check if a given object implements the ModelObjectDto interface.
 */
export function instanceOfModelObjectDto(value: object): value is ModelObjectDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('ownedBy' in value) || value['ownedBy'] === undefined) return false;
    return true;
}

export function ModelObjectDtoFromJSON(json: any): ModelObjectDto {
    return ModelObjectDtoFromJSONTyped(json, false);
}

export function ModelObjectDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelObjectDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'object': json['object'],
        'created': json['created'],
        'ownedBy': json['owned_by'],
    };
}

export function ModelObjectDtoToJSON(json: any): ModelObjectDto {
    return ModelObjectDtoToJSONTyped(json, false);
}

export function ModelObjectDtoToJSONTyped(value?: ModelObjectDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'object': value['object'],
        'created': value['created'],
        'owned_by': value['ownedBy'],
    };
}

