/* tslint:disable */
/* eslint-disable */
/**
 * AI Proxy API
 * OpenAI-compatible proxy for llama.cpp with context compression, retry, and tool-call buffering
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ToolFunctionDto } from './ToolFunctionDto';
import {
    ToolFunctionDtoFromJSON,
    ToolFunctionDtoFromJSONTyped,
    ToolFunctionDtoToJSON,
    ToolFunctionDtoToJSONTyped,
} from './ToolFunctionDto';

/**
 * 
 * @export
 * @interface ToolDefinitionDto
 */
export interface ToolDefinitionDto {
    /**
     * 
     * @type {string}
     * @memberof ToolDefinitionDto
     */
    type: string;
    /**
     * 
     * @type {ToolFunctionDto}
     * @memberof ToolDefinitionDto
     */
    _function: ToolFunctionDto;
}

/**
 * Check if a given object implements the ToolDefinitionDto interface.
 */
export function instanceOfToolDefinitionDto(value: object): value is ToolDefinitionDto {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('_function' in value) || value['_function'] === undefined) return false;
    return true;
}

export function ToolDefinitionDtoFromJSON(json: any): ToolDefinitionDto {
    return ToolDefinitionDtoFromJSONTyped(json, false);
}

export function ToolDefinitionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToolDefinitionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        '_function': ToolFunctionDtoFromJSON(json['function']),
    };
}

export function ToolDefinitionDtoToJSON(json: any): ToolDefinitionDto {
    return ToolDefinitionDtoToJSONTyped(json, false);
}

export function ToolDefinitionDtoToJSONTyped(value?: ToolDefinitionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'function': ToolFunctionDtoToJSON(value['_function']),
    };
}

