/* tslint:disable */
/* eslint-disable */
/**
 * AI Proxy API
 * OpenAI-compatible proxy for llama.cpp with context compression, retry, and tool-call buffering
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ToolFunctionDto
 */
export interface ToolFunctionDto {
    /**
     * 
     * @type {string}
     * @memberof ToolFunctionDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ToolFunctionDto
     */
    description?: string;
    /**
     * 
     * @type {object}
     * @memberof ToolFunctionDto
     */
    parameters?: object;
}

/**
 * Check if a given object implements the ToolFunctionDto interface.
 */
export function instanceOfToolFunctionDto(value: object): value is ToolFunctionDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ToolFunctionDtoFromJSON(json: any): ToolFunctionDto {
    return ToolFunctionDtoFromJSONTyped(json, false);
}

export function ToolFunctionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToolFunctionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'parameters': json['parameters'] == null ? undefined : json['parameters'],
    };
}

export function ToolFunctionDtoToJSON(json: any): ToolFunctionDto {
    return ToolFunctionDtoToJSONTyped(json, false);
}

export function ToolFunctionDtoToJSONTyped(value?: ToolFunctionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'parameters': value['parameters'],
    };
}

