/* tslint:disable */
/* eslint-disable */
/**
 * AI Proxy API
 * OpenAI-compatible proxy for llama.cpp with context compression, retry, and tool-call buffering
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FunctionCallDto } from './FunctionCallDto';
import {
    FunctionCallDtoFromJSON,
    FunctionCallDtoFromJSONTyped,
    FunctionCallDtoToJSON,
    FunctionCallDtoToJSONTyped,
} from './FunctionCallDto';

/**
 * 
 * @export
 * @interface ToolCallDto
 */
export interface ToolCallDto {
    /**
     * 
     * @type {string}
     * @memberof ToolCallDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ToolCallDto
     */
    type: string;
    /**
     * 
     * @type {FunctionCallDto}
     * @memberof ToolCallDto
     */
    _function: FunctionCallDto;
}

/**
 * Check if a given object implements the ToolCallDto interface.
 */
export function instanceOfToolCallDto(value: object): value is ToolCallDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('_function' in value) || value['_function'] === undefined) return false;
    return true;
}

export function ToolCallDtoFromJSON(json: any): ToolCallDto {
    return ToolCallDtoFromJSONTyped(json, false);
}

export function ToolCallDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToolCallDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        '_function': FunctionCallDtoFromJSON(json['function']),
    };
}

export function ToolCallDtoToJSON(json: any): ToolCallDto {
    return ToolCallDtoToJSONTyped(json, false);
}

export function ToolCallDtoToJSONTyped(value?: ToolCallDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'function': FunctionCallDtoToJSON(value['_function']),
    };
}

