/* tslint:disable */
/* eslint-disable */
/**
 * AI Proxy API
 * OpenAI-compatible proxy for llama.cpp with context compression, retry, and tool-call buffering
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsageDto
 */
export interface UsageDto {
    /**
     * 
     * @type {number}
     * @memberof UsageDto
     */
    promptTokens: number;
    /**
     * 
     * @type {number}
     * @memberof UsageDto
     */
    completionTokens: number;
    /**
     * 
     * @type {number}
     * @memberof UsageDto
     */
    totalTokens: number;
}

/**
 * Check if a given object implements the UsageDto interface.
 */
export function instanceOfUsageDto(value: object): value is UsageDto {
    if (!('promptTokens' in value) || value['promptTokens'] === undefined) return false;
    if (!('completionTokens' in value) || value['completionTokens'] === undefined) return false;
    if (!('totalTokens' in value) || value['totalTokens'] === undefined) return false;
    return true;
}

export function UsageDtoFromJSON(json: any): UsageDto {
    return UsageDtoFromJSONTyped(json, false);
}

export function UsageDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsageDto {
    if (json == null) {
        return json;
    }
    return {
        
        'promptTokens': json['prompt_tokens'],
        'completionTokens': json['completion_tokens'],
        'totalTokens': json['total_tokens'],
    };
}

export function UsageDtoToJSON(json: any): UsageDto {
    return UsageDtoToJSONTyped(json, false);
}

export function UsageDtoToJSONTyped(value?: UsageDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prompt_tokens': value['promptTokens'],
        'completion_tokens': value['completionTokens'],
        'total_tokens': value['totalTokens'],
    };
}

