/* tslint:disable */
/* eslint-disable */
/**
 * AI Proxy API
 * OpenAI-compatible proxy for llama.cpp with context compression, retry, and tool-call buffering
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ChatCompletionRequestDto,
  ChatCompletionResponseDto,
} from '../models/index';
import {
    ChatCompletionRequestDtoFromJSON,
    ChatCompletionRequestDtoToJSON,
    ChatCompletionResponseDtoFromJSON,
    ChatCompletionResponseDtoToJSON,
} from '../models/index';

export interface CreateCompletionRequest {
    chatCompletionRequestDto: ChatCompletionRequestDto;
}

/**
 * 
 */
export class ChatApi extends runtime.BaseAPI {

    /**
     * Creates request options for createCompletion without sending the request
     */
    async createCompletionRequestOpts(requestParameters: CreateCompletionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['chatCompletionRequestDto'] == null) {
            throw new runtime.RequiredError(
                'chatCompletionRequestDto',
                'Required parameter "chatCompletionRequestDto" was null or undefined when calling createCompletion().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/chat/completions`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChatCompletionRequestDtoToJSON(requestParameters['chatCompletionRequestDto']),
        };
    }

    /**
     * Create a chat completion
     */
    async createCompletionRaw(requestParameters: CreateCompletionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChatCompletionResponseDto>> {
        const requestOptions = await this.createCompletionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChatCompletionResponseDtoFromJSON(jsonValue));
    }

    /**
     * Create a chat completion
     */
    async createCompletion(chatCompletionRequestDto: ChatCompletionRequestDto, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChatCompletionResponseDto> {
        const response = await this.createCompletionRaw({ chatCompletionRequestDto: chatCompletionRequestDto }, initOverrides);
        return await response.value();
    }

}
