/* tslint:disable */
/* eslint-disable */
/**
 * AI Proxy API
 * OpenAI-compatible proxy for llama.cpp with context compression, retry, and tool-call buffering
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

/**
 * 
 */
export class VideosApi extends runtime.BaseAPI {

    /**
     * Creates request options for generateVideo without sending the request
     */
    async generateVideoRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/videos/generations`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Video generation (not implemented — stub 501)
     */
    async generateVideoRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.generateVideoRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Video generation (not implemented — stub 501)
     */
    async generateVideo(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.generateVideoRaw(initOverrides);
    }

}
